---
title: "論文"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 目的
以往由老師發送期中預警給學生時通常學期已過一半，難以在學生遇到學習困難的初期給予協助，希望藉由二一預測系統能提早觀察出哪些學生是需要被特別關心的，藉由前幾學期的修課面向、同儕之間的關係面向、借書面向、欲預測學期的課程面向與老師面向；預測下一學期是否會被二一。

# 資料處理
## 被解釋變數
原始資料為100年至107年學生各科成績分數資料，並無顯示二一紀錄，在此建立被解釋變數“是否被二一”行。

## 修課面向
### 累計被當比例
同學會被二一最直接連想的為此為同學歷年來的修課狀況與紀錄，在此新增變數分別為；累計必修被當比例、累計選修被當比例以及累計通識被當比例作為捕捉修課面向的特徵，選擇比例而非堂數的原因可由<表X>看出；各系對於必選修與通識上的要求並不一樣固使用比例。

<表，做出各系的必選修通識堂數>

### 累計外系修課狀況
外系的修課狀況是否也會影響到二一的預測也是我們想知道的，固加入變數之中，藉由累計外系修課數，觀察同學在於外系修課的狀況，由表X知道各系會因為規定不同，導致外系修課數有所不同，所以在此我們做標準化處理（減班平均處以班標準差）。

<表 顯示各系外系修課數>

### 必修/選修/通識成績表現（pr）（怕會跟累計被當比例用共線的問題，待討論）
## 同儕面向
### 累計群聚指標
相信同學會被二一不僅僅是純粹學習上的問題，也有可能受到同儕之間群聚效應的影響，為了捕捉同學於班上的互動狀況如何，我們創造一新的變數學期(學年)群聚指標以衡量學生在於一學期(學年)的課程之中平均一週會見到多少同班同學；創造作法為藉由學生修課星期與第幾節課來尋找同班同學有多少人也有一起修課，最後藉由表X可觀察出各系的群聚指標會因為各系課程上的差異而有所差異，所以我們再將群聚指標做標準化（減去同班的平均再除以班上的標準差），作為解釋變數。

<表，做出各系的群聚指標>

### 同儕影響力
除了捕捉到班上同學們群聚效果所營造出的學習環境外，好友之間的影響力也許也是一個可以觀察的變數，我們捕捉各個同學之中與自己課表重複度最高的同學當作該同學最好的朋友，將此好友修課面向的變數也列入欲預測同學的變數中。

###欲預測學期特徵
- 欲預測學期選修數
- 欲預測學期通識數
- 曾被欲預測學期課程的老師當掉次數
- 欲預測學期課程被當過的科目數
- 是否曾經被21











